# Generated by Django 5.0.1 on 2024-01-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactions',
            name='loan_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdrawl'), (3, 'Loan_Request'), (4, 'Loan Paid')]),
        ),
    ]
