# Generated by Django 5.0.1 on 2024-02-07 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_useraccount_user'),
        ('transactions', '0002_usertransactions_loan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactions',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='account.useraccount'),
        ),
    ]
